### ISSUE TITLE
not able to use comment plugin for makefiles

### ISSUE THREAD

**Issue by samdmarshall** [micro-editor/comment-plugin#2]
I am using this plugin and it works great, except for in Makefiles. I've tried adding a new rule to my settings.json file but it doesn't seem to take (possibly because of lack of file extension?) based on the code it looks like it checks the filetype, so I've specified the type as "makefile" in the settings.json and it still doesn't seem to take. Any ideas on this?

**Comment by zyedidia** [comment]
It seems to be working fine for me. Keep in mind that the filetype selection works using globs, not explicit filetypes (which may be a problem) so if you'd like to set the comment type for makefiles you should use:

```json
{
    "{M,m}akefile": {
        "commenttype": "# %s"
    }
}
```

Perhaps there should be a way to explicitly use the filetype, instead of matching a glob to the filename. Perhaps something like:

```json
{
    "ft:makefile": {
        "commenttype": "# %s"
    }
}
```

would be better.

**Comment by samdmarshall** [comment]
Since that seems to be the way that it works in the code, I think would be a better way to implement it in the settings.json file.
